spring:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://locker_manager_db:3306/mysql_database
    username: mysql_user
    password: mysql_password

  jwt:
    secret: jwt_secret

  chain:
    api-token: block_sdk_api_token

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: mail_username
    password: mail_password
    properties:
      smtp.auth: true
      mail:
        smtp:
          starttls:
            enable: true
            required: true
    test-connection: true

server:
  servlet:
    encoding:
      charset: utf-8

logging:
  level:
    org:
    hibernate:
      SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE